"""retirando milissecundos do created_at do user ; criando model para Product

Revision ID: 5861f3b02296
Revises: b9252c15bfff
Create Date: 2024-09-10 21:44:57.093437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5861f3b02296'
down_revision = 'b9252c15bfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('preco', mysql.FLOAT(), nullable=False),
    sa.Column('quant', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
