"""alterando de activate para active; add nullable false às colunas altered_at e active

Revision ID: b5f6a42b0b58
Revises: 6d08618d39fb
Create Date: 2024-09-16 20:11:23.651280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5f6a42b0b58'
down_revision = '6d08618d39fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('altered_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('activate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('altered_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('active')

    # ### end Alembic commands ###
